import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Thema from "./components/thema/Thema";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="flex flex-row p-3 gap-6 font-bold text-3xl border justify-between items-start">
            <Link href="/">HOME</Link>
            <Thema />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
